parameters:
  pool: ''

jobs:
- job: ${{ parameters.pool.os }}_Build
  pool: ${{ parameters.pool }}
  displayName: '🔨 ${{ parameters.pool.os }} Build and Test'
  templateContext:
    outputs:
    - output: pipelineArtifact
      displayName: '🌐 Publish Logs'
      condition: always()
      targetPath: '$(Build.SourcesDirectory)/vscode-dotnet-runtime-extension/dist/test/functional/logs'
      artifactName: '${{ parameters.pool.os }} logs'
  steps:
  - template: install-node.yaml
  - ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
    - script: build.cmd
      displayName: 💻 Build Windows
      condition:
    - script: test.cmd
      displayName: 🔍 Test Windows
  - ${{ if eq(variables['Agent.OS'], 'Linux') }}:
    - bash: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
      displayName: 🎮 Start xvfb
  - ${{ if or(eq(variables['Agent.OS'], 'Darwin'), eq(variables['Agent.OS'], 'Linux')) }}:
    - script: ./build.sh
      displayName: 🐧 Build Mac and Linux
      condition:
    - script: ./test.sh
      displayName: 🔎 Test Mac and Linux
      env: {DISPLAY: ':99.0'}