parameters:
  pool: ''

jobs:
  - template: install-node.yml
  - job: TSLint
    pool: ${{ parameters.pool }}
    displayName: '🧶 TSLint'
    steps:
    - bash: |
        npm install --cache /temp/empty-cache
        npm install tslint --reg https://registry.npmjs.org/ --verbose
        npm run lint
      displayName: 🧶 Run Lint
