trigger:
  batch: true
  branches:
    include:
    - main
  tags:
    include:
    - SDK-v*
    - Runtime-v*
pr:
  autoCancel: false
  branches:
    include:
    - '*'

variables:
- name: Codeql.Enabled
  value: true

parameters:
- name: pools
  type: object
  default:
  - name: NetCore-Svc-Public
    image: 1es-ubuntu-2204-pt
    os: linux
  - name: NetCore-Svc-Public
    image: macOS-latest
    os: macOS
  - name: NetCore-Svc-Public
    image: 1es-windows-2022-open
    os: windows

stages:
- stage: o # o is just used so it looks like a bullet point in the output of devops
  jobs:
  - ${{ each image in parameters.pools }}:
    - template: pipeline-templates/build-test.yaml
      parameters:
        pool:
          name: ${{ image.name }}
          image: ${{ image.image }}
          os: ${{ image.os }}
  - template: pipeline-templates/upstream-verify.yaml
    parameters:
      pool:
        name: $(DncEngInternalBuildPool)
        image: 'windows-latest'
        os: windows
  - template: pipeline-templates/lint.yaml
    parameters:
      pool:
        name: $(DncEngInternalBuildPool)
        image: 'windows-latest'
        os: windows
  - template: pipeline-templates/package-vsix.yaml
    parameters:
      pool:
        name: $(DncEngInternalBuildPool)
        image: 'windows-latest'
        os: windows