trigger:
  batch: true
  branches:
    include:
    - main
  tags:
    include:
    - SDK-v*
    - Runtime-v*
pr:
  autoCancel: false
  branches:
    include:
    - '*'

variables:
- name: Codeql.Enabled
  value: true

parameters:
- name: pools
  type: object
  default:
  - name: $(DncEngPublicBuildPool)
    image: ubuntu-latest
    os: linux
  - name: $(DncEngPublicBuildPool)
    image: macOS-latest
    os: macOS
  - name: $(DncEngPublicBuildPool)
    image: windows-latest
    os: windows

stages:
- stage: Build
  jobs:
  - ${{ each image in parameters.pools }}:
    - template: pipeline-templates/build-test.yaml
      parameters:
        pool:
          name: ${{ image.name }}
          image: ${{ image.image }}
          os: ${{ image.os }}
  - template: pipeline-templates/upstream-verify.yaml
    parameters:
      pool:
        vmImage: 'windows-latest'
  - template: pipeline-templates/lint.yaml
    parameters:
      pool:
        vmImage: 'windows-latest'
  - template: pipeline-templates/package-vsix.yaml
    parameters:
      pool:
        vmImage: 'windows-latest'